services:
  bitbucket:
    build: .
    container_name: bitbucket-server
    ports:
      - "7990:7990"
      - "7999:7999"
    volumes:
      - bitbucket-data:/var/atlassian/application-data/bitbucket
    environment:
      - BITBUCKET_HOME=/var/atlassian/application-data/bitbucket
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/bitbucket
      - SPRING_DATASOURCE_USERNAME=bitbucket
      - SPRING_DATASOURCE_PASSWORD=bitbucketpassword
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:13
    container_name: bitbucket-postgres
    environment:
      POSTGRES_DB: bitbucket
      POSTGRES_USER: bitbucket
      POSTGRES_PASSWORD: bitbucketpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  bitbucket-data:
  postgres-data:
